import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from "@vercel/speed-insights/next"


import "./globals.css";

// const inter = GeistSans({ subsets: ["latin"] });
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistMono.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <div className="bg-white dark:bg-black h-screen">
          <div className="fixed inset-0 max-w-6xl mx-auto h-screen bg-primary p-24 bg-zinc-50 dark:text-white dark:bg-zinc-900"></div>

          <div className="max-w-6xl mx-auto relative p-5 sm:px-24 bg-bllue-100 dark:bg-zinc-900">
            <Navbar />
            {children}
            <Footer />
            <Analytics />
          </div>
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
